---
title: "Conferences"
toc: true
toc-location: right 
link-external-newwindow: true
---

## 2025
**XVIII EAAE Congress**, Bonn, Germany, [Link](https://www.ilr1.uni-bonn.de/eaaecongress2025/en){target="_blank"}  
– *Maximizing Policy Impact: The Value of Information in Designing Agri-environmental Policy*, Kremmydas, Dimitrios; Baldoni, Edoardo; Rey Vicario, Dolores; Tillie, Pascal  
– *Environmental and Economic Impacts of a Tax on Mineral N Fertilizers*, Helming, John; Krisztin, Tamas; Müller, Marc; Kremmydas,
Dimitrios; Rey Vicario, Dolores; Scherer, Hugo; Sckokai, Paolo; Stepanyan, Davit; Varacca, Alessandro; Koutchadé, Obafèmi; Alain, Carpentier; Femenia, Fabienne  
– *Farm-level effects of the Enhanced Conditionality in the CAP*, Rey Vicario, Dolores;
Kremmydas, Dimitrios; Baldoni, Edoardo; Tillie, Pascal  
– *Enhancing IFM-CAP Calibration: Integrating Risk Preferences from Behavioral Experiment*, in organised session 'Incorporating Results from Behavioural Experimental Methods in Agro-Economic Modelling', Kremmydas Dimitris, Rey Dolores, Tillie Pascal
- *Exploring the Future of the CAP: Insights from the IFM-CAP Model*, in organised session 'Advancing Farm Modeling for CAP Policy Analysis: Building a Collaborative Network', Kremmydas Dimitrios, Rey Vicario Dolores, Tillie Pascal 
- *A Framework for Extending Farm Models with Sustainable Farming Practices and Adoption of Eco-schemes*, in organised session 'Advancing Farm Modeling for CAP Policy Analysis: Building a Collaborative Network', Kremmydas Dimitrios, Rey Vicario Dolores, Ciaian Pavel, Tillie Pascal
- *Challenges To Better Represent Water In Micro-Economic Models: The Case Of IFMCAP (Individual Farm Model for Common Agricultural Policy Analysis)*, in organised session 'Sustainable Water Use in Agriculture: from Economic Modelling to Policy Design', Rey-Vicario Dolores, Kremmydas Dimitrios, Baldoni, Edoardo, Tillie Pascal
- <br><br>

## 2024
– **European Regional Science Association Congress (ERSA2024 )**, Azores, Portugal. *Drought effects on agricultural productivity*  

– **32nd International Conference of Agricultural Economists (ICAE)**, New Delhi, India. Caetano, B., et al., incl. Kremmydas D. *How Improved Animal Welfare Standards in the EU Might Affect Farmers and Consumers in the Medium Term*  

– **EcoMod2024 - International Conference on Economic Modeling and Data Science**, Izmir, Turkey. *Deep learning based emulation of complex economic models*  

– **29th Annual Conference of the European Association of Environmental and Resource Economists (EREAE)**, Leuven, Belgium. *Do organic farming policies need to be more target-oriented to achieve the desired environmental benefits?*, : Organic farming policy targeting  
<br><br>

## 2023
– **XVII Congress of European Association of Agricultural Economists (EAAE)**, Rennes, France. Kremmydas et al. *The EU Target For Organic Farming: Potential Budgetary, Farm and Market Impacts Of Two Alternative Pathways*  

– **97th Annual Conference of the Agricultural Economics Society (AES)**, Warwick University, UK.  Invited speaker on the plenary session "Opportunities and failures of policy on organic agriculture", chaired by Dr Alisa Spiegel (Thünen Institute, Germany): 'Opportunities and Failures of Policy on Organic Agriculture' – Other speakers are Dr Nicolas Lampkin (Thünen Institute, Germany), Prof. Simone Severini (UNITUS, Italy) and Dr Sharon Raszap Skorbiansky (US Department of Agriculture, Economic Research Service)
<br><br>

## 2022
– **181th seminar of European Association of Agricultural Economists (EAAE)**, Berlin, Germany. Kremmydas, D., Ciaian, P., Baldoni, E., Tillie, P. *Modeling organic conversion in an EU-wide farm model* 
<br><br>

## 2021
– **16th conference of the Hellenic association of agricultural economists – ETAGRO international section in agricultural economics**, Athens, Greece. Petsakos, A., Espinosa, M., Perni, A., Kremmydas, D., & Ciaian, P.  *The impact of post-2020 cap reform proposal on farmers’ income and the environment: the case of Greece* 

– **XIII Congreso de Economía Agroalimentaria, Asociación Española de Economía Agroalimentaria**, Cartagena, Spain. Petsakos, A., Kremmydas, D., Espinosa Bayal, M. Á., Perni Llorente, Á., & Ciaian, P.  *Economic and environmental effects of the post-2020 cap reform proposal in spain: a farm level assessment*
<br><br>

## 2019
– **172th seminar of European Association of Agricultural Economists (EAAE)**, Brussels, Belgium. Kremmydas, D., Kampas, A., Rozakis, S., & Vlachos, G. *CAP regionalization trade-off analysis: environmental versus socioeconomic priorities*  

– **HAICTA 2017 (Revised Papers 2019)**: *CAP 2020 Regionalization DSS*
<br><br>

## 2018
– **167th seminar of European Association of Agricultural Economists (EAAE)**, Puławy, Poland.  Mantziaris, Stamatis & Kremmydas, Dimitrios & Karanikolas, Pavlos. (2018). A sequential mathematical modeling approach for estimating supply curves for energy crops under different policy scenarios: A Greek case study  

– **162th seminar of European Association of Agricultural Economists (EAAE)**, Budapest, Hungary. Kremymdas Dimitris, Kampas Athanasios, Rozakis Stelios, Tsiboukas Konstantinos, Vlahos George, CAP regionalization scheme in Greece: A rapid policy assessment method 

– **8th International Conference on Information and Communication Technologies in Agriculture, Food & Environment (HAICTA)**, Chania, Greece. Kremmydas D., Malliapis M., Nellas L., Polymeros A., Rozakis S., Tsiboukas K. CAP 2020 Regionalization Design: A Decision Support System
<br><br>

## 2015 and before

– **7th International Conference on Information and Communication Technologies in Agriculture, Food and Environment (HAICTA 2015)**, Kavala, Greece. Maliappis M., & Kremmydas D. An Online Analytical Processing (OLAP) Database for Agricultural Policy Data: a Greek Case Study

– **1st International Symposium on Operational Rsearch (BALCOR 2011)**, Thessaloniki, Greece. Best paper award. Kremmydas D., Haque M. I., & Rozakis S.Enhancing Web-Spatial DSS interactivity with parallel computing: The case of bio-energy economic assessment in Greece

– **10th IASTED International Congress on Parallel and Distributed Computing and Networks (IASTED PDCN 2011)**, Innsbruck, Austria. Mamalid B., Pantziou G., Kremmydas D., & Dimitropoulos G.  Reexamining the parallelization schemes for standard full tableau simplex method on distributed memory environments
